package com.ironclad.clangoals.components.tracking.npcs;

import java.util.Set;
import java.util.function.Predicate;
import joptsimple.internal.Strings;
import lombok.Value;

/**
 * When an NPC isn't actually an NPC but we want it to be treated as one
 * or to serve as a name->id mapping for use with KC chat events.
 */
@Value
class Mapping
{
	/**
	 * The name of the NPC as it appears in the chat message.
	 * This will be generated by use of {@link MessageMatcher}
	 */
	String name;
	/**
	 * The ID to assign to the NPC on submission.
	 */
	int id;
	/**
	 * The blacklist for all variants of this NPC (if any), these will not be tracked
	 * using the standard damage tracking and instead will be ignored.
	 */
	Set<Integer> blacklist;

	public static final Predicate<Mapping> VALIDATOR = mapping -> mapping != null && !Strings.isNullOrEmpty(mapping.name) && mapping.blacklist != null;
}
